import GroundTurkeyBurrito2 from "../assets/ground-turkey-burrito-2.png";
import ChickenStuffedSweetPotato from "../assets/chicken-stuffed-sweet-potato.png";

export const RecipesList = [
  {
    name: "Ground Turkey Burrito",
    link: "ground-turkey-burrito",
    page: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    creator: "Chris Heria",
    time: "15 Min",
    calories: "451",
    carbs: "29g",
    proteins: "53g",
    fats: "21g",
  },
  {
    name: "Chiken and Veggies",
    link: "chiken-and-veggies",
    page: "ChikenAndVeggies",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "460",
    carbs: "34g",
    proteins: "50g",
    fats: "12g",
    // times: 0.58 to 4,38,
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    page: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Salmon Salad",
    link: "salmon-salad",
    page: "SalmonSalad",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "493",
    carbs: "22 g",
    proteins: "46 g",
    fats: "22 g",
    // timing 10.15 to 13.2,
  },
  {
    name: "Steak with greek salad",
    link: "salmon-salad",
    page: "SalmonSalad",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "416",
    carbs: "18 g",
    proteins: "40 g",
    fats: "19 g",
    // https://www.youtube.com/watch?v=-ZaE51yD000
    // timing:
  },
  {
    name: "Baked Chicken Wings and Celery",
    link: "salmon-salad",
    page: "SalmonSalad",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "475",
    carbs: "4 g",
    proteins: "40 g",
    fats: "31 g",
    // timing 10.15 to 13.2,
  },
  {
    name: "Tuna Sandwich",
    link: "salmon-salad",
    page: "SalmonSalad",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "379",
    carbs: "39 g",
    proteins: "46 g",
    fats: "6 g",
    // timing 10.15 to 13.2,
  },
  {
    name: "Protein Pasta and Chicken",
    link: "salmon-salad",
    page: "SalmonSalad",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "495",
    carbs: "39 g",
    proteins: "60 g",
    fats: "6 g",
    // timing 10.15 to 13.2,
  },

  {
    name: "Chicken Stuffed Sweet Potato",
    link: "chicken-stuffed-sweet-potato",
    page: "ChickenStuffedSweetPotato",
    image: ChickenStuffedSweetPotato,
    time: "15 Min",
    calories: "455",
    carbs: "40 g",
    proteins: "53 g",
    fats: "5 g",
    // timing 10.15 to 13.2,
  },
];
