import GroundTurkeyBurrito2 from "../assets/ground-turkey-burrito-2.png";

export const RecipesList = [
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
];
