import GroundTurkeyBurrito2 from "../assets/ground-turkey-burrito-2.png";

export const RecipesList = [
  {
    name: "Ground Turkey Burrito",
    link: "ground-turkey-burrito",
    page: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    creator: "Chris Heria",
    time: "15 Min",
    calories: "123",
    carbs: "321g",
    proteins: "27g",
    fats: "91g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "test12",
    link: "test-123",
    page: "Test123",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321g",
    proteins: "27g",
    fats: "91g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
  {
    name: "Ground Turkey Burrito",
    link: "GroundTurkeyBurrito",
    image: GroundTurkeyBurrito2,
    time: "15 Min",
    calories: "123",
    carbs: "321 g",
    proteins: "27 g",
    fats: "91 g",
    // stats: { carbs: "123", proteins: "123", fats: "123" },
  },
];
